.\" Manpage for jellyfin-autorefresh-new-releases.
.\" Contact sayantan[dot]santra689[at]gmail[dot]com to correct errors or typos.
.TH man 1 "August 2025" "jellyfin-autorefresh-new-releases"
.SH NAME
jellyfin-autorefresh-new-releases
.SH CONFIG
There should be a config file named config.json in the $XDG_CONFIG_HOME/jellyfin-autorefresh-new-releases/ directory.
It should be a valid json file with "baseURI" and "key" entries. It's recommended that you use a local/internal URI for better performance.
.SH AUTHOR
Sayantan Santra sayantan[dot]santra689[at]gmail[dot]com
